title: A Functional Digestive Metabolic Network for TTS
description: Zisheng Wang, Xulong Zhang

theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/fishishappyandfree/fishishappyandfree.github.io/
